app:
  port: 3000
  # namespace:
  # The base path for this application.  Leave empty or omit for none.
  namespace: /site
  # trustProxy:
  # Whether to set the Express 'trust proxy' setting, which tells Express to
  # use the X-Forwarded-* headers to get client information like IP address and
  # protocol.
  trustProxy: true
logging:
  # level:
  # The minimum log level that will be shown in console output.  Levels are:
  # silly:0, input:1, verbose:2, prompt:3, debug:4, http:4.5, info:5, data:6,
  # help:7, warn:8, error:9
  level: http
