app:
  port: 3000
  namespace: /media
  trustProxy: true
  secret: this is not a very good secret
logging:
  level: info
player:
  mediaPath: /media/htpc/media
  commands:
    start: 'DISPLAY=:0 omxplayer "%f"'
    kill: 'killall omxplayer.bin'
  controls:
    play: ' '
    pause: ' '
    exit: 'q'
    seek:
      # Escape sequences obtained using xxd command
      -30: "\x1b\x5b\x44" # left arrow
      +30: "\x1b\x5b\x43" # right arrow
      -600: "\x1b\x5b\x42" # down arrow
      +600: "\x1b\x5b\x41" # up arrow
  exitTimeout: 500
